version: '3.7'

services:
  prod:
    image: accept-front-docker
    restart: always
    container_name: accept-front-prod
    network_mode: host
    build:
      context: ./
    networks:
      internet:

networks:
  internet:
    name: internet
